### ISSUE TITLE
[FIX] Scheme.sql 최신화

### ISSUE THREAD

**Issue by Gyaak** [Kernel360/E2E2-TALKKA#132]
## 수정 후 기능
table ddl 최신화 및 bus_location 테이블 apiCallNo 삭제

**Comment by JuneParkCode** [comment]
schema.sql 을 우선 삭제하도록 함.
- Hibernate 의 ddl create 활용하며 `data.sql` 에서 insert 구문만 별도로 활용...

**Comment by JuneParkCode** [comment]
#133
