### ISSUE TITLE
[FEAT]  버스 지하철 정적 데이터 db 적재

### ISSUE THREAD

**Issue by Gyaak** [Kernel360/E2E2-TALKKA#67]
## 기능
- 버스 지하철 정적 데이터 db 적재
  - [x] 버스 노선 정적 데이터
  - [x] 버스 정거장 정적 데이터
  - [x] 버스 경유정거장 정적 데이터
  - [ ] 지하철 역 정적 데이터
  - [ ] 지하철 운행시간표 정적 데이터
  - [ ] 지하철 혼잡도 정적 데이터

**Comment by JuneParkCode** [comment]
#70 #71
