### ISSUE TITLE
[FEAT] 버스 관련 정적 데이터 가공 SQL 작성

### ISSUE THREAD

**Issue by JuneParkCode** [Kernel360/E2E2-TALKKA#70]
## 기능
- @Gyaak : 버스 관련 정적 데이터 수집 및 가공
- @JuneParkCode  : 가공된 데이터 DB에 밀어넣는 SQL 코드 작성

### 정적 데이터 획득 및 가공
- BMS 버스 인가정보로부터 필요한 버스 노선 정보 획득
- 해당 데이터 기초 정제
- route station / station 분리
- 최종적으로 route station / route / station 데이터 획득 

### DB SQL 코드 작성
- Schema.sql 작성
- csv 파일 load data 스크립트 작성
- api_route_id, api_station_id -> route_id, station_id 매칭
- db 초기화 스크립트 작성

**Comment by Gyaak** [comment]
#67 버스 정적 데이터 연관이슈
